### ISSUE TITLE
Images for ReadMe

### ISSUE THREAD

**Issue by ghost** [MitchellWMckenzie/TriangleBanner#1]
![blue](https://cloud.githubusercontent.com/assets/8935913/25468077/541a2240-2ad0-11e7-9d33-e9806489dfe7.png)
![gray](https://cloud.githubusercontent.com/assets/8935913/25468174/3b8e06a0-2ad1-11e7-84be-39e67c1f903f.png)
![green](https://cloud.githubusercontent.com/assets/8935913/25468177/3b8eca18-2ad1-11e7-8512-cd1d7bd9d8e7.png)
![orange](https://cloud.githubusercontent.com/assets/8935913/25468175/3b8e400c-2ad1-11e7-8f5d-61843c19e275.png)
![pink](https://cloud.githubusercontent.com/assets/8935913/25468172/3b8c2a9c-2ad1-11e7-8631-9a680c7607a0.png)
![purple](https://cloud.githubusercontent.com/assets/8935913/25468173/3b8de8fa-2ad1-11e7-97d5-727878d2da46.png)
![red](https://cloud.githubusercontent.com/assets/8935913/25468176/3b8e29b4-2ad1-11e7-99a7-68850d05ab15.png)
![white](https://cloud.githubusercontent.com/assets/8935913/25468179/3b9eef7e-2ad1-11e7-97f5-52690e22c431.png)
![yellow](https://cloud.githubusercontent.com/assets/8935913/25468180/3b9ef2b2-2ad1-11e7-8786-59da66ceb0be.png)
![banner](https://cloud.githubusercontent.com/assets/8935913/25468181/3ba2296e-2ad1-11e7-8df9-3850ad1a7fca.png)
![anim1](https://cloud.githubusercontent.com/assets/8935913/25468463/42fa8664-2ad3-11e7-99c9-55a78ec19c1b.gif)
![anim3](https://cloud.githubusercontent.com/assets/8935913/25468851/d08a4012-2ad5-11e7-9ce7-c49a2bda2447.gif)
![anim4](https://cloud.githubusercontent.com/assets/8935913/25468850/d0897358-2ad5-11e7-857c-55171c60008f.gif)
![anim2](https://cloud.githubusercontent.com/assets/8935913/25468852/d08b313e-2ad5-11e7-88f9-eeabdf6ff23f.gif)
![brown](https://cloud.githubusercontent.com/assets/8935913/25468178/3b9dafce-2ad1-11e7-9edd-957478486a7f.png)

**Comment by MitchellWMckenzie** [comment]
![anim5](https://cloud.githubusercontent.com/assets/8935913/25505681/22b128d0-2b60-11e7-844e-dc2ec633e377.gif)
![anim6](https://cloud.githubusercontent.com/assets/8935913/25505687/2c9c4bea-2b60-11e7-8225-e3b55eb9bea1.gif)

**Comment by ghost** [comment]
![anim3](https://cloud.githubusercontent.com/assets/8935913/25506232/ded44ebe-2b62-11e7-869b-945a311111cc.gif)
![anim4](https://cloud.githubusercontent.com/assets/8935913/25506234/dee2fd38-2b62-11e7-9bda-5ccfc36f9e2a.gif)
![anim5](https://cloud.githubusercontent.com/assets/8935913/25506235/dee5b866-2b62-11e7-8c4c-b1f53f759628.gif)
![anim6](https://cloud.githubusercontent.com/assets/8935913/25506237/dee5f9ca-2b62-11e7-9953-631feda7947c.gif)
![bottom](https://cloud.githubusercontent.com/assets/8935913/25506310/2e779840-2b63-11e7-85fd-5744689a3fb7.png)

![anim1](https://cloud.githubusercontent.com/assets/8935913/25506239/deea239c-2b62-11e7-8dcf-71e10452c282.gif)
![anim2](https://cloud.githubusercontent.com/assets/8935913/25506238/dee6d840-2b62-11e7-8cdf-ab4320f36bf2.gif)
